### ISSUE TITLE
[DESIGN][SUGGESTION] Add an indicator for public notes

### ISSUE THREAD

**Issue by presi300** [NayamAmarshe/writedown#102]
Concept:

![image](https://github.com/NayamAmarshe/writedown/assets/50592132/71392ef8-8ab1-4e89-8777-f247ba6f2c4b)

[See more](https://www.figma.com/file/FomlS7pqDdfLGRyXP9CUI4/Untitled?type=design&node-id=71%3A2360&mode=design&t=azx5KB20y9pjVFir-1)

**Comment by A-ryan-Kalra** [comment]
working on it

**Comment by abhishek-gaonkar** [comment]
@NayamAmarshe close this..
