### ISSUE TITLE
[BUG] MD does not seem to be properly parsed when reading published (public) posts

### ISSUE THREAD

**Issue by presi300** [NayamAmarshe/writedown#110]
Here is how it looks in the editor (correct):
![image](https://github.com/NayamAmarshe/writedown/assets/50592132/a3056ca8-7638-4f0a-8b0e-cbfed2bfba17)

And here is how it works when viewing a published post from the public URL (bugged):
![image](https://github.com/NayamAmarshe/writedown/assets/50592132/52d07c7f-54af-4e65-9306-23efba0901f7)

**Comment by abhishek-gaonkar** [comment]
Picking this up.. 
Looks like only strike-through isn't working
