### ISSUE TITLE
[REFACTOR] Fuse selectedNoteIdAtom with selectedNoteAtom

### ISSUE THREAD

**Issue by NayamAmarshe** [NayamAmarshe/writedown#112]
We have this unnecessary atom:
https://github.com/NayamAmarshe/writedown/blob/main/stores/selectedChannelIdAtom.ts

That could just be fused with the following atom: https://github.com/NayamAmarshe/writedown/blob/main/stores/postDataAtom.ts

The id would become a part of the object and the selectedNoteId will be replaced in the code.

**Comment by abhishek-gaonkar** [comment]
Taking this up..
Checked the code and modifying the implementation of selectedChannelIdAtom.ts to match that of implementation in postDataAtom.ts

- [ ] Check implementation of selectedChannelIdAtom useAtom in other files
- [ ] Modify to use atoms in postDataAtom

**Comment by abhishek-gaonkar** [comment]
@NayamAmarshe close this..
