### ISSUE TITLE
Editor buttons (check description)

### ISSUE THREAD

**Issue by NayamAmarshe** [NayamAmarshe/writedown#16]
- [ ] Heading ( 1 | 2 | 3 | 4 )
- [ ] Image upload ( cloud || markdown image )
- [ ] Bold
- [ ] Italic
- [ ] Ordered list
- [ ] Unordered list
- [ ] Checkbox
- [ ] Table (optional for now, few people use that)
- [ ] Comment 
- [ ] Quote 
- [ ] Code block
- [ ] URL/link 
- [ ] Strikethrough
- [ ] Underline

**Comment by etareduction** [comment]
> it's not possible to provide free storage forever
Maybe it is 😉 https://github.com/DvorakDwarf/Infinite-Storage-Glitch

**Comment by NayamAmarshe** [comment]
> > it's not possible to provide free storage forever
> 
> Maybe it is wink https://github.com/DvorakDwarf/Infinite-Storage-Glitch

Haha! Sneaky sneaky.

But costs are not an issue. I'm ready to fund this project once we get the new design and optimization out :)
