### ISSUE TITLE
Can't sign up

### ISSUE THREAD

**Issue by diamond00744** [NayamAmarshe/writedown#21]
Got 404 on [signup](https://writedown.app/signup) page

![20230310_062143_firefox](https://user-images.githubusercontent.com/1475378/224215039-caf2cb38-a913-4f90-9261-8a9cb559bdcc.png)

**Comment by NayamAmarshe** [comment]
Yeah, sorry about that. The signup page is not really complete. You can use the login page instead, it will do the same thing :) https://writedown.app/login
