### ISSUE TITLE
Installation/build instructions + ability to disable need for signup/login when running locally

### ISSUE THREAD

**Issue by Footsiefat** [NayamAmarshe/writedown#73]
I would like to either download a binary or have some basic build instructions for running it locally. Also since I would ideally want to run this fully locally I would also like the ability to just disable the need to signups/login completely.

Thanks.

**Comment by NayamAmarshe** [comment]
Hi, I've added the build instructions. We also will create a docker image soon :)
Thanks for the feedback!

Let me know if you run into any issues or anything.
