### ISSUE TITLE
[BUG][PUBLISHING] 404 Error on public viewing link

### ISSUE THREAD

**Issue by NayamAmarshe** [NayamAmarshe/writedown#96]
<img width="466" alt="image" src="https://github.com/NayamAmarshe/writedown/assets/25067102/0dfa382a-45c7-4fee-af95-03a4db358f43">

## Objective:
The objective of this feature is to ensure that when a post is published, the public viewing link is immediately accessible and does not result in a 404 error.

## Problem Statement:
Currently, when a user publishes a post after saving it, the public viewing link leads to a 404 error, indicating that the post is not found. This issue needs to be resolved to provide a smooth publishing experience for the user and ensure that the public link is immediately accessible upon publishing.

### Functional Requirements:

1. **Publish Post**:
    - When a user publishes a post, it should be immediately accessible through the public viewing link without any errors.
    - The system should ensure that the post is made available to the front-end system upon publishing.

2. **Public Viewing Link**:
    - The public viewing link should be valid and accessible immediately after the post is published.
    - The link should direct to the correct post content.

3. **Error Handling**:
    - If there is any issue in publishing the post or making it available, appropriate error messages should be logged and displayed to the user.
    - A fallback mechanism should be in place to ensure the post is accessible as soon as possible.

4. **Logging**:
    - Implement logging to track the status of post publishing and link generation.
    - Log any errors encountered during the process for further analysis.

### Non-functional Requirements:

1. **Performance**:
    - The process of publishing a post and making the link accessible should be efficient and fast.
    - Ensure low latency in serving the public viewing link after publishing.

2. **Scalability**:
    - The solution should handle a high volume of posts and links without degradation of performance.

3. **Reliability**:
    - Ensure high availability and reliability of the post publishing process and public viewing link.

4. **Security**:
    - Ensure that only authorized users can publish posts.
    - Implement security measures to prevent unauthorized access to the publishing process and public viewing links.

5. **Usability**:
    - The publishing process should be straightforward and user-friendly.
    - Clear feedback should be provided to the user upon successful publishing or in case of errors.

## Acceptance Criteria:

1. **Post is accessible**:
    - When a post is published, the public viewing link leads directly to the published post without a 404 error.

2. **Error handling**:
    - If an error occurs during the publishing process, the user is notified, and the error is logged.

3. **Logging**:
    - Logs capture details about the post publishing process, including any errors.

4. **Performance and scalability**:
    - The system should handle a large number of posts being published and linked without any degradation in performance.

## Implementation Plan:

1. **Investigation**:
    - Analyze the current publishing process to identify potential causes of the 404 error.
    - Investigate the integration between the front-end and back-end systems to ensure smooth data flow.

2. **Design**:
    - Update the publishing workflow to guarantee that the post is accessible immediately upon publishing.
    - Design and implement error handling and fallback mechanisms.

3. **Development**:
    - Develop changes to the publishing process and public viewing link generation.
    - Implement logging and monitoring for the publishing process.

4. **Testing**:
    - Perform end-to-end testing manually to verify that posts are accessible immediately after publishing.
    - Test under different conditions, including high load, to ensure performance and scalability.

5. **Deployment**:
    - Deploy the updated system.
    - Monitor the system for any issues post-deployment and address them promptly.

**Comment by A-ryan-Kalra** [comment]
Working on it.
